routes/web.php
<?php

// 'routes/web.php'

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
Route::group(['as' => 'hhquiz.'], function () {
    event(new Routing());
    Route::middleware(['web','admin.user'])->group(function () {
        Route::get('/admin/hhquiz', [IndexController::class, 'index'])->name('index');
    });

    Route::middleware(['web','admin.user'])->group(function () {
        Route::get('/admin/hhquiz/quizzes', [QuizzesController::class, 'index'])->name('quizzes.index');
    });

    event(new RoutingAfter());
});
*/

/*Route::prefix('admin')->middleware('auth')->group(['as' => 'hhquiz.'], function () {

});*/

Route::middleware(['web', 'auth'])
    ->name('hhquiz.admin.')
    ->namespace('Hachim\HHQuiz\Http\Controllers\Admin')
    ->group(function () {
        Route::get('/admin/hhquiz', 'HomeController@index')->name('home');
    });

Route::middleware(['web', 'auth'])
    ->prefix('admin/hhquiz')
    ->name('hhquiz.')
    ->namespace('Hachim\HHQuiz\Http\Controllers')
    ->group(function () {
        //classrooms
        Route::get('/classrooms', 'Admin\Classrooms\IndexController@index')->name('classrooms.index');
        Route::get('/classrooms/ajax/json/search', 'Admin\Classrooms\IndexController@indexAjax')
            ->name('admin.ajax.json.classrooms.search');


        //quizzes
        Route::get('/quizzes', 'Admin\Quizzes\IndexController@index')->name('quizzes.index');
        Route::get('/quizzes/ajax/json/search', 'Admin\Quizzes\IndexController@indexAjax')
            ->name('admin.ajax.json.quizzes.search');
        Route::get('/quizzes/{uuid}', 'Admin\Quizzes\IndexController@getOne')
            ->name('quizzes.get.one')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::get('/quizzes/{uuid}/update', 'Admin\Quizzes\IndexController@updateForm')
            ->name('quizzes.update.form')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::put('/quizzes/{uuid}/update', 'Admin\Quizzes\IndexController@update')
            ->name('quizzes.update.put')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::get('/quizzes/create', 'Admin\Quizzes\IndexController@createForm')
            ->name('quizzes.create.form');
        Route::post('/quizzes/create', 'Admin\Quizzes\IndexController@create')
            ->name('quizzes.create.post');


        /***************************
         * 
         * 
         * Avant (old)
         */
        //quizzes
        //Route::get('/quizzes', 'QuizzesController@index')->name('quizzes.index');


        //quiz_question
        Route::post(
            '/quizzes/{quizId}/questions',
            'QuizQuestionsController@create'
        )->name('quizzes.questions.create.post')
            ->where('quizId', '[0-9]+');
        Route::get(
            '/quizzes/{quizId}/questions',
            'QuizQuestionsController@createForm'
        )->name('quizzes.questions.create.form')
            ->where('quizId', '[0-9]+');

        //questions
        Route::get('/questions', 'QuestionsController@index')
            ->name('questions.index');
        Route::get('/questions/create', 'QuestionsController@createForm')
            ->name('questions.create.form');
        Route::post('/questions/create', 'QuestionsController@create')
            ->name('questions.create.post');
        Route::get('/questions/{uuid}/update', 'QuestionsController@updateForm')
            ->name('questions.update.form')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::put('/questions/{uuid}/update', 'QuestionsController@update')
            ->name('questions.update.put')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::get('/questions/{uuid}', 'QuestionsController@getOne')
            ->name('questions.get.one')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');

        //user_groups
        Route::get('/groups', 'GroupsController@index')->name('groups.index');
        Route::get('/groups/create', 'GroupsController@createForm')
            ->name('groups.create.form');
        Route::post('/groups/create', 'GroupsController@create')
            ->name('groups.create.post');
        Route::get('/groups/{id}/update', 'GroupsController@updateForm')
            ->name('groups.update.form')
            ->where('id', '[0-9]+');
        Route::put('/groups/{id}/update', 'GroupsController@update')
            ->name('groups.update.put')
            ->where('id', '[0-9]+');
        Route::get('/groups/{id}', 'GroupsController@getOne')
            ->name('groups.get.one')
            ->where('id', '[0-9]+');

        //question_groups
        //ajax
        Route::get('/ajax/json/questions/groups/search', 'AjaxJsonQuestionGroupsSearchController')
            ->name('ajax.json.questions.groups.search');
        Route::get('/questions/groups', 'QuestionGroupsController@index')
            ->name('questions.groups.index');
        Route::get('/questions/groups/create', 'QuestionGroupsController@createForm')
            ->name('questions.groups.create.form');
        Route::post('/questions/groups/create', 'QuestionGroupsController@create')
            ->name('questions.groups.create.post');
        Route::get(
            '/questions/groups/{uuid}/update',
            'QuestionGroupsController@updateForm'
        )->name('questions.groups.update.form')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::put(
            '/questions/groups/{uuid}/update',
            'QuestionGroupsController@update'
        )->name('questions.groups.update.put')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::get('/questions/groups/{uuid}', 'QuestionGroupsController@getOne')
            ->name('questions.groups.get.one')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');

        //question_choices
        Route::get(
            '/questions/{question}/choices/create',
            'QuestionChoicesController@createForm'
        )->name('questions.choices.create.form')
            ->where('question', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::post(
            '/questions/{question}/choices/create',
            'QuestionChoicesController@create'
        )->name('questions.choices.create.post')
            ->where('question', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::get(
            '/questions/{question}/choices/{choice}/update',
            'QuestionChoicesController@updateForm'
        )->name('questions.choices.update.form')
            ->where(['question' => '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}', 'choice' => '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}']);
        Route::put(
            '/questions/{question}/choices/{choice}/update',
            'QuestionChoicesController@update'
        )->name('questions.choices.update.put')
            ->where(['question' => '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}', 'choice' => '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}']);

        //quiz_groups
        //ajax
        Route::get('/ajax/json/quizzes/groups/search', 'AjaxJsonQuizGroupsSearchController')
            ->name('ajax.json.quizzes.groups.search');
        Route::get('/quizzes/groups', 'QuizGroupsController@index')
            ->name('quizzes.groups.index');
        Route::get('/quizzes/groups/create', 'QuizGroupsController@createForm')
            ->name('quizzes.groups.create.form');
        Route::post('/quizzes/groups/create', 'QuizGroupsController@create')
            ->name('quizzes.groups.create.post');
        Route::get(
            '/quizzes/groups/{uuid}/update',
            'QuizGroupsController@updateForm'
        )->name('quizzes.groups.update.form')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::put(
            '/quizzes/groups/{uuid}/update',
            'QuizGroupsController@update'
        )->name('quizzes.groups.update.put')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
        Route::get('/quizzes/groups/{uuid}', 'QuizGroupsController@getOne')
            ->name('quizzes.groups.get.one')
            ->where('uuid', '[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}');
    });


Route::middleware(['web', 'auth'])
    ->prefix('hhquiz/student-area')
    ->name('hhquiz.student.')
    ->namespace('Hachim\HHQuiz\Http\Controllers\Student')
    ->group(function () {
        //quizzes
        Route::get('/quizzes', 'QuizzesController@index')->name('quizzes.index');
        Route::get('/quizzes/{id}', 'QuizzesController@getOne')
            ->name('quizzes.get.one')
            ->where('id', '[0-9]+');
    });

resources/views/quizzes/groups/create.blade.php
@extends('hhquiz::layouts.quizzes.groups.form')
@php
  $title 		=  'Création d\'un classeur de quiz';
  $url = route('hhquiz.quizzes.groups.create.post');
  $methode = 'POST';
@endphp

resources/views/quizzes/groups/index.blade.php
@extends('adminlte::page')

@section('title', 'Classeurs de quiz')

@section('content_header')
<h1>Les classeurs de quiz</h1>
@stop

@section('content')


<div class="row">
    <div class="col-12">
        <div class="card">
            
            <div class="card-header">
                <a href="{{ route('hhquiz.quizzes.groups.create.form') }}" class="btn btn-success">Créer un classeur</a>
                <div class="card-tools"> 
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i></button>
                </div>
                <div class="input-group-prepend float-right">
                    <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      Filtre dates
                    </button>
                    <ul class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 48px, 0px);">
                      <li class="dropdown-item"><a href="#">Action</a></li>
                      <li class="dropdown-item"><a href="#">Another action</a></li>
                      <li class="dropdown-item"><a href="#">Something else here</a></li>
                      <li class="dropdown-divider"></li>
                      <li class="dropdown-item"><a href="#">Separated link</a></li>
                    </ul>
                  </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table class="table table-bordered table-hover datatable">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Status</th>
                            <th>Créé par</th>
                            <th>Créé le</th>
                            <th>Mise à jour le</th>
                            <th>ID</th>
                            <th width="250">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($groups as $group)
                    <tr>
                        <td>
                            @isset($group->parent->parent->title)
                            <small><a href="{{route('hhquiz.quizzes.groups.get.one',$group->parent->parent->uuid)}}"">{{ $group->parent->parent->title }} </a> / </small>
                            @endisset
                            @isset($group->parent->title)
                        <small><a href="{{route('hhquiz.quizzes.groups.get.one',$group->parent->uuid)}}"">{{ $group->parent->title }} </a> / </small>
                            @endisset
                            <a href="{{route('hhquiz.quizzes.groups.get.one',$group->uuid)}}"">
                            {{$group->title}}
                            </a>
                        </td>
                        <td>
                            @if ($group->is_enabled == 1)
                                <span class="badge badge-success">Actif</span>
                            @else 
                                <span class="badge badge-danger">Inactif</span>
                            @endif
                        </td>
                        <td>{{$group->author->name}}</td>
                        <td>{{$group->created_at}}</td>
                        <td>{{$group->updated_at}}</td>
                        <td>{{$group->id}}</td>
                        <td class="project-actions text-right">
                            <a class="btn btn-primary btn-sm" href="{{ route('hhquiz.quizzes.groups.get.one', $group->uuid) }}">
                              <i class="fas fa-eye">
                              </i>
                            </a>
                            <a class="btn btn-info btn-sm" href="{{ route('hhquiz.quizzes.groups.update.form', $group->uuid) }}">
                              <i class="fas fa-edit">
                              </i>
                            </a>
                            <form action="#" method="POST" onsubmit="return confirm('Message confirmation');" style="display: inline-block;">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@stop

@section('css')
<!--
<link rel="stylesheet" href="/css/admin_custom.css">
-->
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('vendor/datatables/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/datatables-plugins/responsive/css/responsive.bootstrap4.min.css') }}">
@stop

@section('js')
<script src="{{ asset('vendor/datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-plugins/responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('vendor/datatables-plugins/responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    $(function() {
        $('.datatable').DataTable({
            "paging": false,
            "lengthChange": true,
            "searching": false,
            "ordering": true,
            "info": false,
            "autoWidth": true,
            "responsive": true,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/French.json"
            }
        });
    });
</script>
@stop

resources/views/quizzes/groups/show.blade.php
@extends('adminlte::page')

@section('title', 'Classeur Quiz')

@section('content_header')
<h1>Classeur Quiz :
    @isset($group->parent->parent->parent->title)
    <small><a href="{{route('hhquiz.quizzes.groups.get.one',$group->parent->parent->parent->id)}}"">{{ $group->parent->parent->parent->title }} /</a></small>
    @endisset
    @isset($group->parent->parent->title)
    <small><a href="{{route('hhquiz.quizzes.groups.get.one',$group->parent->parent->id)}}"">{{ $group->parent->parent->title }} /</a></small>
    @endisset 
    @isset($group->parent->title)
    <small><a href="{{route('hhquiz.quizzes.groups.get.one',$group->parent->id)}}"">{{ $group->parent->title }} /</a></small>
    @endisset
    {{ $group->title }} 
</h1>
@stop

    @section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-info"></i>
                        Information
                    </h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                          <i class="fas fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <dl>
                        <dt>{{ $group->description }}</dt>
                    </dl>
                    <table class="table table-sm">
                        <tbody>
                            <tr>
                                <td>Id :</td>
                                <td>{{ $group->id }}</td>
                            <tr>
                                <td>Créé le :</td>
                                <td>{{ $group->created_at }}</td>
                            <tr>
                                <td>Mis à jour le :</td>
                                <td>{{ $group->updated_at }}</td>
                            </tr>
                            <tr>
                                <td>Créé par :</td>
                                <td>{{ $group->author->name }}</td>
                            </tr>
                            <tr>
                        </tbody>
                    </table>
                    <a class="btn btn-info btn-sm" href="{{ route('hhquiz.quizzes.groups.update.form', $group->id) }}">
                        <i class="fas fa-edit">
                        </i>
                        Modifier
                    </a>
                    <form action="#" method="POST" onsubmit="return confirm('Message confirmation');" style="display: inline-block;">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"> Supprimer</i></button>
                    </form>
                    <a class="btn btn-primary btn-sm" href="{{ route('hhquiz.quizzes.index') }}?quiz_group={{ $group->id}}">
                        <i class="fas fa-eye">
                        </i>
                        Voir tous les quqiz du classeur
                    </a>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- ./col -->
    </div>

    @stop

resources/views/quizzes/groups/update.blade.php
@extends('hhquiz::layouts.quizzes.groups.form')
@php
  $title 		=  'Mise à jour d\'un classeur de quiz';
  $url = route('hhquiz.quizzes.groups.update.put', ['uuid' => request('uuid')]);
  $methode = 'PUT';
@endphp